[package]
name = "grpc_health_check"
version = "0.1.0"
edition = "2018"
include = ["build.rs"]

[[bin]]
name = "grpc-health-check"
path = "src/main.rs"
doctest = false

[dependencies]
mimalloc = { version = "0.1.25", optional = true }
prost = "0.7.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
structopt = "0.3"
tokio = { version = "1.4.0", features = ["full"] }
tonic = { version = "0.4.1", features = ["prost", "tls", "transport"] }

[build-dependencies]
tonic-build = { version = "0.4.1", features = ["transport", "prost"] }

[profile.release]
lto = true
panic = "abort"